"use client"

import { Saira } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { ProductFilterContextProvider } from "@/contexts/productsFilterContext";
import { Provider } from "@/utils/providers";

const saira = Saira({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
});

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <Provider>
          <ProductFilterContextProvider>
            <Header />
            {children}
          </ProductFilterContextProvider>
        </Provider>
      </body>
    </html>
  );
}
