import { Saira } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { ProductFilterContextProvider } from "@/contexts/productsFilterContext";

const saira = Saira({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <ProductFilterContextProvider>
          <Header />
          {children}
        </ProductFilterContextProvider>
      </body>
    </html>
  );
}
